config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  belongs_to :post, class_name: 'Post', counter_cache: :comments_counter

  after_save :update_comments_counter

  validates :text, presence: true,
                   length: { minimum: 3, maximum: 250, too_long: '%<count>s is the maximum characters allowed',
                             too_short: '%<count>s is the minimum characters allowed' }

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  belongs_to :post, counter_cache: :likes_counter

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_counter

  validates :title, presence: true, length: { minimum: 5, maximum: 250,
                                              too_long: '%<count>s characters is the maximum allowed' }
  validates :comments_counter, numericality: { only_integer: true },
                               comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def return_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def return_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_email_confirmation, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end

  def check_email_confirmation
    return unless user_signed_in? && !current_user.confirmed?

    flash.now[:alert] = 'Please verify your email address before accessing your account.'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = post.find(params[post_id])
    # @posts = Post.all.includes(:comments)
    @user = @post.author
    @comment = Comment.new(comment_params)
  end

  def create
    @post = Post.find(params[:post_id])
    @user = @post.author
    @new_comment = Comment.create(post: @post, author: @user, text: comment_params['text'])

    if @new_comment.valid?
      flash[:success] = 'Commented successfully'
      respond_to do |format|
        format.html do
          redirect_to request.referrer, notice: 'Comment added'
        end
      end
    else
      flash[:alert] = 'Error creating the comment'
    end
  end

  private

  def comment_params
    params.require(:new_comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:posts_id])
    @user = ApplicationController.current_user
    @new_like = Like.create(author: @user, post: @post)

    if @new_like.valid?
      flash[:success] = 'Like added successfully'
      respond_to do |format|
        format.html { redirect_to request.referrer, notice: 'Liked' }
      end
    else
      flash[:alert] = 'Error adding a like'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'posts'

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
    @current_user = params[:user_id]
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:alert] = 'Post was not created.'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'users'
  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out_and_redirect
    else
      find_user
    end
  end

  def sign_out_and_redirect
    sign_out current_user
    redirect_to root_path
  end

  def find_user
    @user = User.find(params[:id])
    @posts = @user.return_recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/new.html.erb
<section class='create'>
  <h1>Add a comment</h1>

  <%= form_with model: @comment, url: user_post_comments_path do |form| %>
    <div class="form-field">
      <%= form.label :text, 'Comment' %>
      <%= form.text_area :text, placeholder: 'Enter comment', class: 'border1' %>
    </div>

    <div class="actions">
      <%= form.submit 'Add Comment', class: 'btn btn-create' %>
    </div>
  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="flash-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Blog App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag "styles" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Blog App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag "styles" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/index.html.erb
<div>
<%= render "shared/usertile",user: @user %>
<div class="posts">
<% @posts.each do |post|%>
  <%= render "shared/posttile", post:post %>
  <%= render "shared/comments",comments: post.return_recent_comments.includes(:author) %>
<% end %>
<button type="button" class="pagination_button">
    Pagination
</button>
</div>
</div>

app/views/posts/new.html.erb
<%= render "shared/posts_form", url:user_posts_path(user_id:@current_user) %>

app/views/posts/show.html.erb
<div class="container">
<%= render "shared/posttile", post:@post %>
<%= render "shared/comments", comments: @post.comments.includes(:author) %>
<%= render "shared/comments_form", url:user_post_comments_path(user_id:@user.id ,post_id:@post.id), locals:{post_id:@post.id}%>
</div>>

app/views/shared/_comments.html.erb
<div class="comments_container">
<h4>Comments:</h4>
<% comments.each do |comment| %>
<p><%=comment.author.name %>: <%= comment.text%></p>
<%end%>
</div>

app/views/shared/_comments_form.html.erb
<%= form_with url:url, method: :post,scope: :new_comment,local: true do |f|%>
  <div class="comment-form">
    <h3>Add comment</h3>
    <%= f.text_area :text, size:'70x3', placeholder: "Add a comment"%>
    <%= f.submit%>
  </div>
<%end%>

app/views/shared/_posts_form.html.erb
<%= form_with model: @post, url: user_posts_path(current_user), method: :post, local: true, scope: :post do |form| %>
  <div class="posts_form">
    <h3>Add new post:</h3>
    
    <%= form.label :title,"blog title" %>
    <%= form.text_field :title %>
    <%= form.label :text,"blog text" %>
    <%= form.text_area :text, size:'70x4' %>
    <%= form.submit%>
  </div>
<%end%>

app/views/shared/_posttile.html.erb
  <%= link_to user_post_path(post.author.id,post.id) do%>
  
  <div class="post_tile">
    <h3>Post #: <%= post.id %> <%=post.title %></h3>
    <h4>Author: <%= post.author.name%></h4>
    <p><%= post.text%></p>

    <%= link_to user_post_likes_path(user_id: post.author.id,post_id: post.id), data:{turbo_method: :post} do %>
      <button class="likes_button">
        Like
      </button>
    <%end%>
    <p class="comments_likes" >Comments: <%= post.comments_counter%> Likes: <%= post.likes_counter%> </p>
  </div>
  <%end%>

app/views/shared/_usertile.html.erb
<%= link_to user_path(user.id) do %>

<div>
  <li class="user_list_item">
    <img class="profile_photo" src=<%= user.photo%> alt="profile image">
    <div class="details">
      <h2 class="username">
        <%= user.name %>
      </h2>

      <p class="posts_count">Number of posts: <%= user.posts.count %></p>
    </div>
  </li>
</div>
<% end %>

app/views/users/index.html.erb
<% if @users.empty? %>
    <p>There are no users</p>
<% else %>
    <p class="current-user">Logged in as: <%= current_user.name %></p>
    <%= link_to new_user_post_path(user_id: current_user.id),class:"new-post-btn" do%> 
        <button>
        Create New Post
        </button>
    <% end %>
    <ul id='current-users' >
        <p>Current Users</p>
        <% @users.each do |user| %>
        <li>
            <img src=<%= user.photo %> alt="image">
            <div>
                <h2><%= link_to user.name , {:action => 'show', :id => user.id} %></h2>
                <p>Number of posts: <%= user.posts_counter %> </p>
            </div>
        </li>
        <% end %>
    </ul>
    <button>
        <%= link_to 'Sign out',  destroy_user_session_path, method: :delete %>
    </button>
<% end %>

app/views/users/show.html.erb
<div class="user_details">
    <%= render "shared/usertile",user: @user  %>
<div class="user_bio">

<h3>Bio:</h3>
    <%= @user.bio %>
</div>
<div class="posts">
    <% @user.return_recent_posts.each do |post| %>
    <%= render 'shared/posttile', post: post %>
<% end %>

</div>

<%= link_to user_posts_path(@user.id),class: 'button_link'  do%> 

<button class="all_posts_button" type="button">
    See all posts
</button>

<% end %>
</div>